### ISSUE TITLE
When importing an entity, multiple refers of entry type attribute are registered.

### ISSUE THREAD

**Issue by hinashi** [dmm-com/pagoda#65]
## Reproduction procedure
1. Create an Entity.
Name: TestEntity

2. Create an Attribute.
Name: ref, Type: entry, refer: TestEntity

3. Create an Entry.
Name: TestEntity

4. Import the YAML file.
```
EntityAttr:
- create_user: user_name
  id: xxxx
  entity: TestEntity
  is_mandatory: false
  name: ref
  refer: TestEntity
  type: 1
```
